// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Kita ubah ke DIRECT_URL agar proses db push ke Supabase tidak diblokir
    url: process.env["DIRECT_URL"], 
  },
});